export type MockServerData = {
  titles: string[],
  descriptions: string[],
  previews: string[],
  photos: string[],
  users: string[],
  emails: string[],
  avatars: string[],
  postDates: string[],
  cities: string[],
  isPremium: string[],
  isFavorite: string[],
  ratings: string[],
  housingTypes: string[],
  roomAmounts: string[],
  guestAmounts: string[],
  rentPrices: string[],
  features: string[],
  commentsAmounts: string[],
  coordinates: string[],
}
